import { randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { CLAUDE_CONFIG_DIR, CODEX_HOME } from "./config";

/**
 * The operator's own standing instructions, for a Codex work cycle.
 *
 * A Claude cycle loads `~/.claude/CLAUDE.md` and every `~/.claude/rules/*.md`
 * from the mounted config directory; a Codex cycle loads none of them, because
 * Codex reads `AGENTS.md` instead. Measured on 0.153.4, 2026-10-07: Codex loads
 * `$CODEX_HOME/AGENTS.md` as its global instructions — `codex debug
 * prompt-input` showed a marker from it, and so did the session file of a
 * `codex exec --ignore-user-config`, so the flag every cycle carries does not
 * drop it. So this writes that file from the Claude sources before every Codex
 * cycle, and an operator edits their rules in one place for both providers.
 *
 * A repository's own `CLAUDE.md` is the other half and is not here:
 * `buildCodexArgs` passes `project_doc_fallback_filenames`, which makes Codex
 * read it where a repository has no `AGENTS.md`.
 *
 * **Rewritten every cycle, as `codexRules.ts` rewrites the pkill denial**, and
 * for a sharper reason here: `CODEX_HOME` is the agents' own directory, so a
 * cycle can replace this file, and a run that wrote itself standing
 * instructions would otherwise hand them to every Codex run after it. Rewriting
 * bounds that to the cycle that did it. **So the file is this app's, whatever
 * is in it:** one that lacked the header line used to be left alone as the
 * operator's, and that is exactly the shape a planted file would take to
 * survive — a cycle that wrote its own `AGENTS.md` without the header would
 * have made it permanent. The file did not exist before this module; an
 * operator's standing instructions for Codex go in `~/.claude/rules`, where
 * Claude reads them too.
 */

export const CODEX_INSTRUCTIONS_FILE = path.join(CODEX_HOME, "AGENTS.md");

/** The first line of every file this module writes, telling a reader where to edit instead. */
export const GENERATED_HEADER =
  "<!-- Generated by UsageFoundry from ~/.claude/CLAUDE.md and ~/.claude/rules/. Edit those; this file is rewritten before every Codex work cycle. -->";

/** A rules file larger than this is not instructions, and is left out rather than truncated. */
const MAX_SOURCE_BYTES = 64 * 1024;

export interface InstructionSource {
  /** What the section is headed with: `CLAUDE.md`, or the rules file's name. */
  name: string;
  text: string;
}

/**
 * Strip a YAML frontmatter block and read the one key that changes meaning.
 *
 * `paths:` is Claude Code's condition — a rule with it applies only to work on
 * matching files — and Codex has no such mechanism, so the condition is kept
 * as a sentence above the rule instead of being dropped with the rest of the
 * metadata, which would make a Python rule read as one for every file.
 */
export function splitFrontmatter(text: string): { body: string; paths: string[] } {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text);
  if (!match) return { body: text, paths: [] };
  const paths: string[] = [];
  let inPaths = false;
  for (const line of match[1].split(/\r?\n/)) {
    if (/^paths\s*:/.test(line)) {
      inPaths = true;
      const inline = /^paths\s*:\s*\[(.*)\]\s*$/.exec(line);
      if (inline) {
        for (const item of inline[1].split(",")) {
          const value = item.trim().replace(/^["']|["']$/g, "");
          if (value) paths.push(value);
        }
        inPaths = false;
      }
      continue;
    }
    if (inPaths) {
      const item = /^\s*-\s*(.+?)\s*$/.exec(line);
      if (item) {
        paths.push(item[1].replace(/^["']|["']$/g, ""));
        continue;
      }
      if (/^\S/.test(line)) inPaths = false;
    }
  }
  return { body: text.slice(match[0].length), paths };
}

/**
 * The file's text from its sources, or null when there is nothing to say.
 * Pure, and under test.
 *
 * One section per source, headed with its name, in the order given — which
 * the caller makes `CLAUDE.md` first and then the rules sorted by name, the
 * order nothing about Claude Code's own loading contradicts. An empty source
 * contributes nothing; a source of nothing but frontmatter likewise.
 */
export function composeCodexInstructions(sources: readonly InstructionSource[]): string | null {
  const sections: string[] = [];
  for (const source of sources) {
    const { body, paths } = splitFrontmatter(source.text);
    const text = body.trim();
    if (!text) continue;
    const scope =
      paths.length > 0
        ? `Applies when working on files matching: ${paths.map((p) => `\`${p}\``).join(", ")}.\n\n`
        : "";
    sections.push(`## ${source.name}\n\n${scope}${text}`);
  }
  if (sections.length === 0) return null;
  return `${GENERATED_HEADER}\n\n# The operator's standing instructions\n\n${sections.join("\n\n")}\n`;
}

/** What the run loop is told, for a log line when it is not `written`. */
export type CodexInstructionsDelivery =
  | { kind: "written"; file: string }
  | { kind: "none" }
  | { kind: "unavailable"; reason: string };

function readSources(): InstructionSource[] {
  const sources: InstructionSource[] = [];
  const read = (file: string, name: string) => {
    try {
      const stat = fs.statSync(file);
      if (!stat.isFile() || stat.size > MAX_SOURCE_BYTES) return;
      sources.push({ name, text: fs.readFileSync(file, "utf8") });
    } catch {
      // Absent is the ordinary case for `CLAUDE.md`; nothing to say.
    }
  };
  read(path.join(CLAUDE_CONFIG_DIR, "CLAUDE.md"), "CLAUDE.md");
  let names: string[] = [];
  try {
    names = fs.readdirSync(path.join(CLAUDE_CONFIG_DIR, "rules"));
  } catch {
    names = [];
  }
  for (const name of names.filter((n) => n.endsWith(".md")).sort()) {
    read(path.join(CLAUDE_CONFIG_DIR, "rules", name), `rules/${name}`);
  }
  return sources;
}

/**
 * Write, refresh or remove `$CODEX_HOME/AGENTS.md` before a Codex cycle.
 *
 * Never throws: a cycle without the operator's instructions still does its
 * work, so a failure here is a log line rather than the refusal the pkill
 * rules earn. Written atomically and world-readable, `codexRules.ts`' pattern,
 * because the writer is the server and the reader is the cycle's uid.
 */
export function prepareCodexInstructions(): CodexInstructionsDelivery {
  const file = CODEX_INSTRUCTIONS_FILE;
  const text = composeCodexInstructions(readSources());
  if (text === null) {
    // Nothing to carry: take the file away rather than leave rules the
    // operator has since deleted, or text a cycle planted, standing for every
    // Codex run.
    try {
      fs.rmSync(file, { force: true });
    } catch {
      // A file that cannot be removed is reported by the next write attempt.
    }
    return { kind: "none" };
  }

  const tmp = `${file}.tmp-${randomBytes(6).toString("hex")}`;
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(tmp, text);
    fs.chmodSync(tmp, 0o644);
    fs.renameSync(tmp, file);
    return { kind: "written", file };
  } catch (err) {
    try {
      fs.rmSync(tmp, { force: true });
    } catch {
      // The rename is what matters.
    }
    return { kind: "unavailable", reason: `${file} could not be written: ${(err as Error).message}` };
  }
}
